### ISSUE TITLE
Setting imagePreview dimensions

### ISSUE THREAD

**Issue by priyesh-diukar** [supnate/icropper#7]
Hello,

Is there an api to set imagePreview dimensions?
The example demo.html shows only small preview. I want to show the same effect on a full screen size.
How can i achieve this?
Also can I set the cropping aspect ration to 16:9 ?

Any help will be highly appreciated.
Thank you :)

**Comment by supnate** [comment]
You should be able to use `ratio` parameter.
```
var ic = new ICropper(
	'cropperContainer'    //Container id
	,{
		ratio: 16/9    //Set aspect ratio of the cropping area
		,image: 'demo.png'
		,preview: [
				'previewSmall'  //Preview node id
		]
	}
);
```

**Comment by priyesh-diukar** [comment]
Supnate. Thank you for your quick reply.
I see the rendered cropping region is always centered inside the cropper div.
Can i set Left, Top, Width, Height property  for my preview to render the initial cropping region other than center?

**Comment by supnate** [comment]
Sorry, there's not such configuration yet...

**Comment by priyesh-diukar** [comment]
Okay. I will figure the rest out. Thanks once again for your help.

**Comment by supnate** [comment]
No problem.
