### ISSUE TITLE
save

### ISSUE THREAD

**Issue by fahamjv** [supnate/icropper#8]
how to save result ?

**Comment by supnate** [comment]
icropper is only the UI part. You need to save result by yourself.

**Comment by fahamjv** [comment]
@supnate  so , i write this 



		var infoWidth = document.getElementById('width');
		var infoHeight = document.getElementById('height');
		var infoX = document.getElementById('x');
		var infoY = document.getElementById('y');
		var infoImage = document.getElementById('image');

		var ic2 = new ICropper(
			'cropperContainer2'
			,{
				ratio: 0
				,image: '{{asset('image/demo.png')}}'
				,onChange: function(info){	//onChange must be set when constructing.
					infoWidth.value = info.w;
					infoHeight.value = info.h;
					infoX.value = info.l;
					infoY.value = info.t;
					//infoImage.value = 'asdasdadads';

				}
				,preview: [
					'previewSmall2'
				]
			});
		//use bindPreview to dynamically add preview nodes
		ic2.bindPreview('previewBig2');

	

	
		$(document).ready(function(){
			$("button").click(function(){
                $.ajax({
                    type: "POST",
                    url: "http://127.0.0.1:8000/api/",
                    data: new FormData($('#coppingform')[0]),
                    processData: false,
                    contentType: false,
                    success: function (data) {
                        $("#divider").html(data);
                    }
                });
			});
		});
	`
but i don't know how i can send image to api with (post method)

**Comment by supnate** [comment]
I think the image should have been sent to api by this code:
```
data: new FormData($('#coppingform')[0]),
```
That's how to send image to API using ajax post request.

**Comment by fahamjv** [comment]
@supnate  i tried this . its send everything in form to api , except image

**Comment by supnate** [comment]
I searched an article: http://makitweb.com/how-to-upload-image-file-using-ajax-and-jquery/
It looks like you need to attach file to form data:
```
var fd = new FormData();
var files = $('#file')[0].files[0];
fd.append('file',files);
```
